#!/bin/bash

# exemplo de comentarios
echo "digite seu nome; "
read nome

echo "ola $nome !!!"
echo "Digite um numero inteiro:"
read numA
echo "Digite um outro numero inteiro:"
read numB

echo "Soma: $(($numA + $numB))"
echo "Subtração: $(($numA - $numB))"
echo "Multipliação: $(($numA * $numB))"
echo "Divisão: $(($numA / $numB))"
echo "Resto da divisão: $(($numA % $numB))"

